version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: laravelpassword
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network
    command: --default-authentication-plugin=mysql_native_password

  laravel:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    volumes:
      - ./backend:/var/www
      - /var/www/vendor
      - laravel_storage:/var/www/storage/app/public
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: laraveluser
      DB_PASSWORD: laravelpassword
    networks:
      - app_network
    command: >
      sh -c "
      mkdir -p bootstrap/cache storage/framework/{cache,sessions,views} &&
      chmod -R 775 bootstrap/cache storage &&
      php artisan config:cache &&
      php artisan route:cache &&
      php artisan view:cache &&
      php artisan storage:link &&
      php artisan serve --host=0.0.0.0 --port=8000
      "

  next:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: next_app
    restart: unless-stopped
    depends_on:
      - laravel
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: https://zavodshow.ru/api
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    container_name: nginx_server
    restart: unless-stopped
    depends_on:
      - next
      - laravel
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/autoreload.sh:/docker-entrypoint.d/autoreload.sh
    networks:
      - app_network

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    depends_on:
      - nginx
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
  laravel_storage:
