version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: laravelpassword
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
    networks:
      - app_network

  laravel:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - laravel_storage:/var/www/storage
      - laravel_public:/var/www/public
    env_file:
      - ./backend/.env
    command: >
      sh -c "while ! nc -z mysql_db 3306; do sleep 1; done &&
          composer install &&
          php artisan migrate --force &&
          php artisan config:cache &&
          php artisan storage:link &&
          php artisan db:seed --force &&
          php-fpm"
    networks:
      - app_network

  next:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: next_app
    restart: unless-stopped
    depends_on:
      - laravel
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: /api
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - laravel_storage:/var/www/storage:ro
    depends_on:
      - laravel
      - next
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  laravel_storage:
    driver: local
  laravel_public:
    driver: local
