version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: laravelpassword
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "--password=$$(echo $$MYSQL_ROOT_PASSWORD)",
        ]
      interval: 5s
      timeout: 10s
      retries: 20
      start_period: 20s
    networks:
      - app_network

  laravel:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - laravel_storage:/var/www/storage
      - laravel_public:/var/www/public
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=laraveluser
      - DB_PASSWORD=laravelpassword
    command: >
      sh -c "
      echo 'Waiting for MySQL to be ready...'
      while ! mysqladmin ping -h mysql -u root --password=$$(echo $$MYSQL_ROOT_PASSWORD) --silent; do
        echo 'MySQL not ready yet - sleeping'
        sleep 5
      done
      echo 'MySQL is ready!'
      php artisan migrate --force
      php-fpm
      "
    networks:
      - app_network

  next:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: next_app
    restart: unless-stopped
    depends_on:
      - laravel
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: /api
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - laravel_storage:/var/www/storage:ro
    depends_on:
      - laravel
      - next
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
  laravel_storage:
  laravel_public:
